### ISSUE TITLE
 Game crashed on load. 

### ISSUE THREAD

**Issue by beouwolfe** [nbrichau/vanillaextension#1]
Minecraft 1.16.1
Forge 32.0.106
vanillaextension-1.16.1-1.0.5.2.jar

Game crashed on load. Received the following message

Vanilla Extension (vanillaextension) encountered an error during the load_registries phase

Here is a pastebin link to the latest log https://pastebin.com/ct6d6uea

**Comment by Ketheroth** [comment]
So I found my error. I'm a dumbass.  
I forget to reobfuscate my code. I used the wrong gradle command.
