### ISSUE TITLE
Can not build Trapdoors

### ISSUE THREAD

**Issue by DheBoss** [nbrichau/vanillaextension#3]
![2020-08-11_21 27 08](https://user-images.githubusercontent.com/69538165/89940250-83197c00-dc19-11ea-81d5-5690c767378c.png)
when i want to build a trapdoor on the craftingtable I only can build the Wall with the same Wood. (with the receipebook or per hand)

**Comment by Ketheroth** [comment]
Oh. I didn't remember it was the same recipe as trapdoor. I will definitely fix it in nex update.

**Comment by DheBoss** [comment]
It is not exactly the same recipe. The walls want the upper 6 fields and the trapdoors the lower 6 ones. But now it becomes walls in both variants.

**Comment by Ketheroth** [comment]
I changed the recipes for plank walls to be like : 
```
 # 
###
###
```
where `#` is a plank.  
And that give 7 walls.

**Comment by DheBoss** [comment]
Thanks for ur fast response and fixing it

**Comment by DheBoss** [comment]
Same with glass_pane (colored, too)

**Comment by Ketheroth** [comment]
Oh yeah it's impossible to craft glass pane now

**Comment by Ketheroth** [comment]
Done, like plank walls
