### ISSUE TITLE
Unable to craft glass panes - just shows glass wall now for that recipe

### ISSUE THREAD

**Issue by TheOrionsun** [nbrichau/vanillaextension#4]
MC 1.15.2
Forge 31.2.41
Vanilla Extension 1.15.2-1.0.5

I am now unable to make glass panes. JEI will show the craft correctly, but in the table it shows Glass Wall as the output from six glass blocks. 

What is the correct recipe for the glass wall? I can't think it would be the same as glass panes....so is forge changing it?

Thank you,

**Comment by TheOrionsun** [comment]
I created a new test world MC 1.15.2 with only Vanilla Extension and the recipe for glass panes is still not working.

I did try to roll back Forge to 31.2.36 and it did not fix the issue.

**Comment by Ketheroth** [comment]
Ah, yeah, I forgot to make this change on the 1.15 version. It's just fixed in the 1.16.

For a temporary solution I suggest you tou use the mod [polymorph](https://www.curseforge.com/minecraft/mc-mods/polymorph)

**Comment by Ketheroth** [comment]
hey, the bug is fixed on the latest version (1.15.2-1.0.6)

**Comment by TheOrionsun** [comment]
Great! 

Thank you
