### ISSUE TITLE
oak trapdoor doesn't open

### ISSUE THREAD

**Issue by nosevole** [nbrichau/vanillaextension#5]
Hi nbrichau, thankyou so much for all your hard work on this mod, it's excellent :) I'm currently creative testing it for use on our new server and have discovered that the oak trapdoors don't open on right-click. They respond to redstone however, as if they were iron. 
I'm not sure if this is intentional or not, but I thought I'd let you know in case it was overlooked.
Thanks again, take care xx

**Comment by Ketheroth** [comment]
Thanks for liking my mod!  
It wasn't intentional that log trapdoors doesn't open on right-click. I removed it by making them possible to be stripped with an axe right-click.  
That's gonna be fixed soon.

**Comment by Ketheroth** [comment]
Hey, the bug is fixed now in version 1.16.3-1.0.11
