### ISSUE TITLE
Game crashes while loading. Possibly a conflict with another mod ?

### ISSUE THREAD

**Issue by ghost** [nbrichau/vanillaextension#8]
[crash-2022-04-30_12.37.23-client.txt](https://github.com/Ketheroth/vanillaextension/files/8596712/crash-2022-04-30_12.37.23-client.txt)

**Comment by Ketheroth** [comment]
It's my fault, I made the azalea stairs check for properties it doens't have

**Comment by Ketheroth** [comment]
now fixed in 9e6dc9eda12f999b1974b1ed65dfcf408f4e9cd7
